spring.application.name=api

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/api?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
# 'update' automatically updates the schema structure in the database based on your Java entities
spring.jpa.hibernate.ddl-auto=update

# Displays executed SQL queries in the console (useful for development)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
